M48
; DRILL file KiCad 10.0.6 date 2026-10-04T21:29:12
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-10-04T21:29:12-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.6
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.900
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X119.2Y-51.75
X126.0Y-51.75
T2
X105.25Y-55.0
X105.25Y-146.0
X194.75Y-55.0
X194.75Y-146.0
M30
